### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by stovberpv** [AlburIvan/SlickForm#2]
When clicking on NEXT button with no username input or with 1 char input (words or numbers).
The same for email and password.

![image](https://user-images.githubusercontent.com/13037514/27608135-fb92ba34-5b8e-11e7-97d6-f407e6827083.png)

java.lang.IllegalAccessError: Illegal class access: 'com.alburivan.slickform.tooltip.SimpleTooltip' attempting to access 'android.support.v7.widget.AppCompatPopupWindow' (declaration of 'com.alburivan.slickform.tooltip.SimpleTooltip'

`at com.alburivan.slickform.tooltip.SimpleTooltip.configPopupWindow(SimpleTooltip.java:150)
                                                                         at com.alburivan.slickform.tooltip.SimpleTooltip.init(SimpleTooltip.java:145)
                                                                         at com.alburivan.slickform.tooltip.SimpleTooltip.<init>(SimpleTooltip.java:141)
                                                                         at com.alburivan.slickform.tooltip.SimpleTooltip.<init>(SimpleTooltip.java:69)
                                                                         at com.alburivan.slickform.tooltip.SimpleTooltip$Builder.build(SimpleTooltip.java:577)
                                                                         at com.alburivan.slickform.SlickForm.showWarningDialog(SlickForm.java:543)
                                                                         at com.alburivan.slickform.SlickForm.processFormField(SlickForm.java:316)
                                                                         at com.alburivan.slickform.SlickForm.processFormState(SlickForm.java:280)
                                                                         at com.alburivan.slickform.SlickForm.access$200(SlickForm.java:63)
                                                                         at com.alburivan.slickform.SlickForm$1.onClick(SlickForm.java:171)`

![image](https://user-images.githubusercontent.com/13037514/27607235-dd09e9dc-5b8b-11e7-9b9a-07dd89707da3.png)

![image](https://user-images.githubusercontent.com/13037514/27607258-f5fa4a22-5b8b-11e7-95f5-8be3080388bf.png)

![image](https://user-images.githubusercontent.com/13037514/27607288-15667e62-5b8c-11e7-8214-168914abad2e.png)

![image](https://user-images.githubusercontent.com/13037514/27607349-416f16b8-5b8c-11e7-8802-6655a0f6b512.png)

![image](https://user-images.githubusercontent.com/13037514/27607416-7e8904d2-5b8c-11e7-822d-99811e5aca41.png)

![image](https://user-images.githubusercontent.com/13037514/27607518-cd2453e4-5b8c-11e7-91cf-ea66c39f9ee6.png)

## For password field new exception:
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                                         at com.alburivan.slickform.SlickForm.processFormFieldEnd(SlickForm.java:340)
                                                                         at com.alburivan.slickform.SlickForm.changeTarget(SlickForm.java:359)
                                                                         at com.alburivan.slickform.SlickForm.access$300(SlickForm.java:63)
                                                                         at com.alburivan.slickform.SlickForm$2.onAnimationEnd(SlickForm.java:328)
                                                                         at android.view.animation.Animation$3.run(Animation.java:381)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)`

![image](https://user-images.githubusercontent.com/13037514/27608505-7940198a-5b90-11e7-821a-184a34fc2e2e.png)

![image](https://user-images.githubusercontent.com/13037514/27608515-85325780-5b90-11e7-9dcb-9f9265e1371f.png)

**Comment by jeancsanchez** [comment]
I think it can help #4
